// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResidentialHallManagement.Data;

#nullable disable

namespace ResidentialHallManagement.Data.Migrations.HallManagement
{
    [DbContext(typeof(HallManagementDbContext))]
    [Migration("20251208075248_AddStudentDashboardEntities")]
    partial class AddStudentDashboardEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedHall", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("AssignedStudentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ASSIGNED_S_TYPE");

                    b.Property<string>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValue("YES")
                        .HasColumnName("ASSIGNED_CURRENT");

                    b.HasKey("StudentId", "HallId");

                    b.HasIndex("HallId");

                    b.ToTable("ASSIGNED_HALL", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedRoom", b =>
                {
                    b.Property<int>("AssignedRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ASS_ROOM_SID");

                    b.Property<DateTime?>("ActualCheckout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ACTUAL_CHECKOUT");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ALLOCATION_STATUS");

                    b.Property<int>("AssignedHallId")
                        .HasColumnType("int")
                        .HasColumnName("ASS_HALL_H_ID");

                    b.Property<string>("BedNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("BED_NUMBER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ASS_ROOM_EDATE");

                    b.Property<DateTime?>("ExpectedCheckout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EXPECTED_CHECKOUT");

                    b.Property<int>("RoomHallId")
                        .HasColumnType("int")
                        .HasColumnName("R_H_ID");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("R_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ASS_ROOM_SDATE");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID");

                    b.HasKey("AssignedRoomId");

                    b.HasIndex("RoomId", "RoomHallId");

                    b.HasIndex("StudentId", "AssignedHallId");

                    b.ToTable("ASSIGNED_ROOM", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.DesignatedHall", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("T_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DES_ADMIN_ROLE");

                    b.Property<DateTime?>("RelieveDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DES_ADMIN_RDATE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DES_ADMIN_SDATE");

                    b.HasKey("TeacherId", "HallId");

                    b.HasIndex("HallId");

                    b.ToTable("DESIGNATED_HALL", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("E_ID");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("E_NAME");

                    b.HasKey("EventId");

                    b.ToTable("EVENTS", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.EventInfo", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("E_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("E_INFO_EDATE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("E_INFO_SDATE");

                    b.HasKey("EventId", "HallId");

                    b.HasIndex("HallId");

                    b.ToTable("EVENT_INFO", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Fee", b =>
                {
                    b.Property<int>("FeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("F_ID");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("F_CATEGORY");

                    b.Property<int>("FeeAmount")
                        .HasColumnType("int")
                        .HasColumnName("F_AMNT");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("F_NAME");

                    b.HasKey("FeeId");

                    b.ToTable("FEES", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Hall", b =>
                {
                    b.Property<int>("HallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    b.Property<int>("HallCapacity")
                        .HasColumnType("int")
                        .HasColumnName("H_CAPACITY");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("H_NAME");

                    b.Property<string>("HallType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("H_TYPE");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("H_LOCATION");

                    b.HasKey("HallId");

                    b.ToTable("HALL", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("REQUEST_ID");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("HALL_ID");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ISSUE");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PRIORITY");

                    b.Property<DateTime?>("ResolvedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RESOLVED_ON");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("ROOM_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SUBMITTED_ON");

                    b.Property<string>("TechnicianNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TECHNICIAN_NOTE");

                    b.HasKey("RequestId");

                    b.HasIndex("StudentId");

                    b.HasIndex("RoomId", "HallId");

                    b.ToTable("MAINTENANCE_REQUESTS");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("M_ID");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("M_DATE");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("M_ROUND");

                    b.Property<string>("Tournament")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("M_TOURN");

                    b.HasKey("MatchId");

                    b.ToTable("MATCHES", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.MatchInfo", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TEAM_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("M_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("M_INFO_RESULT");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("int")
                        .HasColumnName("M_INFO_WINNER");

                    b.HasKey("TeamId", "MatchId");

                    b.HasIndex("MatchId");

                    b.ToTable("MATCH_INFO", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Participation", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("E_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("EventRole")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("E_ROLE");

                    b.HasKey("StudentId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("PARTICIPATION", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAYMENT_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("INVOICE_NUMBER");

                    b.Property<string>("Method")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("METHOD");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PAYMENT_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("PaymentId");

                    b.HasIndex("StudentId");

                    b.ToTable("PAYMENTS");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("R_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("R_AVAILABILITY");

                    b.Property<string>("Block")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("R_BLOCK");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("R_FLOOR");

                    b.Property<int>("RoomCapacity")
                        .HasColumnType("int")
                        .HasColumnName("R_CAPACITY");

                    b.Property<string>("RoomName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("R_NAME");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("R_NUMBER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_STATUS");

                    b.Property<string>("Wing")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("R_WING");

                    b.HasKey("RoomId", "HallId");

                    b.HasIndex("HallId");

                    b.ToTable("ROOMS", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomChangeRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("REQUEST_ID");

                    b.Property<string>("AdminRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ADMIN_REMARKS");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PROCESSED_DATE");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("REASON");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("REQUEST_DATE");

                    b.Property<int>("RequestedHallId")
                        .HasColumnType("int")
                        .HasColumnName("REQUESTED_HALL_ID");

                    b.Property<string>("RequestedRoomId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("REQUESTED_ROOM_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("RequestId");

                    b.HasIndex("StudentId");

                    b.HasIndex("RequestedRoomId", "RequestedHallId");

                    b.ToTable("ROOM_CHANGE_REQUESTS");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Sponsor", b =>
                {
                    b.Property<int>("SponsorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SP_ID");

                    b.Property<string>("Contact")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SP_CONTACT");

                    b.Property<string>("Manager")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SP_MANAGER");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SP_NAME");

                    b.HasKey("SponsorId");

                    b.ToTable("SPONSORS", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Sponsorship", b =>
                {
                    b.Property<int>("SponsorId")
                        .HasColumnType("int")
                        .HasColumnName("SP_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("E_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SPON_CMNT");

                    b.Property<int?>("SponsorshipAmount")
                        .HasColumnType("int")
                        .HasColumnName("SPON_AMNT");

                    b.HasKey("SponsorId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("SPONSORSHIP", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Staff", b =>
                {
                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID")
                        .HasColumnOrder(0);

                    b.Property<string>("StaffId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ST_ID")
                        .HasColumnOrder(1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("ST_AGE");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ST_E_DATE");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ST_H_DATE");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ST_JOB_ID");

                    b.Property<int?>("Salary")
                        .HasColumnType("int")
                        .HasColumnName("ST_SALARY");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ST_NAME");

                    b.Property<string>("Wing")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("ST_WING");

                    b.HasKey("HallId", "StaffId");

                    b.ToTable("STAFFS", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("S_BLD_GRP");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("S_DOB");

                    b.Property<string>("Department")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("S_DEPARTMENT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("S_EMAIL");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_EMERGENCY_NAME");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("S_EMERGENCY_PHONE");

                    b.Property<string>("EmergencyRelation")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("S_EMERGENCY_RELATION");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("S_FATHER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("S_GENDER");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("S_MOBILE");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("S_MOTHER");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_PRM_ADDR");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("S_PHOTO_URL");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("S_RELIGION");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("S_STATUS");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("S_NAME");

                    b.HasKey("StudentId");

                    b.ToTable("STUDENTS", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.StudentFee", b =>
                {
                    b.Property<int>("MemoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ST_FEE_MEMO_ID");

                    b.Property<int>("FeeId")
                        .HasColumnType("int")
                        .HasColumnName("F_ID");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("S_F_LDATE");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_F_MONTH");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("S_F_PDATE");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("S_F_YEAR");

                    b.HasKey("MemoId");

                    b.HasIndex("FeeId");

                    b.HasIndex("StudentId", "HallId");

                    b.ToTable("STUDENTS_FEES", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("T_ID");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("T_DESIG");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("T_NAME");

                    b.HasKey("TeacherId");

                    b.ToTable("TEACHERS", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TEAM_ID");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("TEAM_SPORT");

                    b.HasKey("TeamId");

                    b.HasIndex("HallId");

                    b.ToTable("TEAMS", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.TeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TEAM_ID")
                        .HasColumnOrder(0);

                    b.Property<string>("StudentId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("T_MEM_ROLE");

                    b.HasKey("TeamId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("TEAM_MEMBER", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VIOLATION_ID");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ACTION_TAKEN");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RESOLVED_DATE");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SEVERITY");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("ViolationId");

                    b.HasIndex("StudentId");

                    b.ToTable("VIOLATIONS");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedHall", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("AssignedHalls")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("AssignedHalls")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedRoom", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("AssignedRooms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Room", "Room")
                        .WithMany("AssignedRooms")
                        .HasForeignKey("RoomId", "RoomHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.AssignedHall", "AssignedHall")
                        .WithMany("AssignedRooms")
                        .HasForeignKey("StudentId", "AssignedHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedHall");

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.DesignatedHall", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("DesignatedHalls")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Teacher", "Teacher")
                        .WithMany("DesignatedHalls")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.EventInfo", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Event", "Event")
                        .WithMany("EventInfos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("EventInfos")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId", "HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.MatchInfo", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Match", "Match")
                        .WithMany("MatchInfos")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Team", "Team")
                        .WithMany("MatchInfos")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Participation", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Event", "Event")
                        .WithMany("Participations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("Participations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Payment", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Room", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("Rooms")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomChangeRequest", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("RoomChangeRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Room", "RequestedRoom")
                        .WithMany()
                        .HasForeignKey("RequestedRoomId", "RequestedHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedRoom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Sponsorship", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Event", "Event")
                        .WithMany("Sponsorships")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Sponsor", "Sponsor")
                        .WithMany("Sponsorships")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Staff", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("Staffs")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.StudentFee", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Fee", "Fee")
                        .WithMany("StudentFees")
                        .HasForeignKey("FeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("StudentFees")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.AssignedHall", "AssignedHall")
                        .WithMany("StudentFees")
                        .HasForeignKey("StudentId", "HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedHall");

                    b.Navigation("Fee");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Team", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("Teams")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.TeamMember", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("TeamMembers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Violation", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("Violations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedHall", b =>
                {
                    b.Navigation("AssignedRooms");

                    b.Navigation("StudentFees");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Event", b =>
                {
                    b.Navigation("EventInfos");

                    b.Navigation("Participations");

                    b.Navigation("Sponsorships");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Fee", b =>
                {
                    b.Navigation("StudentFees");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Hall", b =>
                {
                    b.Navigation("AssignedHalls");

                    b.Navigation("DesignatedHalls");

                    b.Navigation("EventInfos");

                    b.Navigation("Rooms");

                    b.Navigation("Staffs");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Match", b =>
                {
                    b.Navigation("MatchInfos");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Room", b =>
                {
                    b.Navigation("AssignedRooms");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Sponsor", b =>
                {
                    b.Navigation("Sponsorships");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Student", b =>
                {
                    b.Navigation("AssignedHalls");

                    b.Navigation("AssignedRooms");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Participations");

                    b.Navigation("Payments");

                    b.Navigation("RoomChangeRequests");

                    b.Navigation("StudentFees");

                    b.Navigation("TeamMembers");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Teacher", b =>
                {
                    b.Navigation("DesignatedHalls");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Team", b =>
                {
                    b.Navigation("MatchInfos");

                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
