// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResidentialHallManagement.Data;

#nullable disable

namespace ResidentialHallManagement.Data.Migrations.HallManagement
{
    [DbContext(typeof(HallManagementDbContext))]
    partial class HallManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ADMIN_NAME");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MODIFIED_DATE");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("USER_ID");

                    b.HasKey("AdminId");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AdminUser", b =>
                {
                    b.Property<int>("AdminUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADMIN_USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("AdminUserId");

                    b.ToTable("admin_users");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedHall", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID")
                        .HasColumnOrder(1);

                    b.Property<string>("AssignedStudentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ASSIGNED_S_TYPE");

                    b.Property<string>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValue("YES")
                        .HasColumnName("ASSIGNED_CURRENT");

                    b.HasKey("StudentId", "HallId");

                    b.HasIndex("HallId");

                    b.ToTable("assigned_hall", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedRoom", b =>
                {
                    b.Property<int>("AssignedRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ASS_ROOM_SID");

                    b.Property<DateTime?>("ActualCheckout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ACTUAL_CHECKOUT");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ALLOCATION_STATUS");

                    b.Property<int>("AssignedHallId")
                        .HasColumnType("int")
                        .HasColumnName("ASS_HALL_H_ID");

                    b.Property<string>("BedNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("BED_NUMBER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ASS_ROOM_EDATE");

                    b.Property<DateTime?>("ExpectedCheckout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EXPECTED_CHECKOUT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("R_ID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ASS_ROOM_SDATE");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID");

                    b.HasKey("AssignedRoomId");

                    b.HasIndex("RoomId", "AssignedHallId");

                    b.HasIndex("StudentId", "AssignedHallId");

                    b.ToTable("assigned_room", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.BoarderRegistry", b =>
                {
                    b.Property<string>("BoarderNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BOARDER_NO");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("BoarderNo");

                    b.HasIndex("StudentId");

                    b.ToTable("boarder_registry", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Hall", b =>
                {
                    b.Property<int>("HallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("H_ID");

                    b.Property<int>("HallCapacity")
                        .HasColumnType("int")
                        .HasColumnName("H_CAPACITY");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("H_NAME");

                    b.Property<string>("HallType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("H_TYPE");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("H_LOCATION");

                    b.HasKey("HallId");

                    b.ToTable("hall", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.HallAdmin", b =>
                {
                    b.Property<int>("HallAdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HALL_ADMIN_ID");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ADMIN_NAME");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ADMIN_ROLE");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("END_DATE");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("HALL_ID");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PHONE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("USER_ID");

                    b.HasKey("HallAdminId");

                    b.HasIndex("HallId");

                    b.ToTable("hall_admins", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("REQUEST_ID");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("HALL_ID");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ISSUE");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PRIORITY");

                    b.Property<DateTime?>("ResolvedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RESOLVED_ON");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("ROOM_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SUBMITTED_ON");

                    b.Property<string>("TechnicianNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TECHNICIAN_NOTE");

                    b.HasKey("RequestId");

                    b.HasIndex("StudentId");

                    b.HasIndex("RoomId", "HallId");

                    b.ToTable("MAINTENANCE_REQUESTS");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("R_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("H_ID")
                        .HasColumnOrder(1);

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int")
                        .HasColumnName("R_AVAILABLE");

                    b.Property<string>("Block")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("R_BLOCK");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("R_FLOOR");

                    b.Property<int>("RoomCapacity")
                        .HasColumnType("int")
                        .HasColumnName("R_CAPACITY");

                    b.Property<string>("RoomName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("R_NAME");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("R_NUMBER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("R_STATUS");

                    b.Property<string>("Wing")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("R_WING");

                    b.HasKey("RoomId", "HallId");

                    b.HasIndex("HallId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomApplicationRequest", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("APPLICATION_ID");

                    b.Property<string>("AdminRemarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADMIN_REMARKS");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("APPLICATION_DATE");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("APPROVAL_DATE");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("APPROVED_BY");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("HALL_ID");

                    b.Property<string>("RequestedRoomIdentity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("REQUESTED_ROOM_IDENTITY");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("ApplicationId");

                    b.HasIndex("HallId");

                    b.HasIndex("StudentId");

                    b.ToTable("room_application_requests", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ASSIGNMENT_ID");

                    b.Property<DateTime?>("ActualCheckout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ACTUAL_CHECKOUT");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ASSIGNMENT_DATE");

                    b.Property<string>("BedNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BED_NUMBER");

                    b.Property<DateTime?>("ExpectedCheckout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("EXPECTED_CHECKOUT");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("HALL_ID");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("NOTES");

                    b.Property<string>("RoomIdentity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ROOM_IDENTITY");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("AssignmentId");

                    b.HasIndex("HallId");

                    b.HasIndex("StudentId");

                    b.ToTable("room_assignments", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomChangeRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("REQUEST_ID");

                    b.Property<string>("AdminRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ADMIN_REMARKS");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PROCESSED_DATE");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("REASON");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("REQUEST_DATE");

                    b.Property<int>("RequestedHallId")
                        .HasColumnType("int")
                        .HasColumnName("REQUESTED_HALL_ID");

                    b.Property<string>("RequestedRoomId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("REQUESTED_ROOM_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STUDENT_ID");

                    b.HasKey("RequestId");

                    b.HasIndex("StudentId");

                    b.HasIndex("RequestedRoomId", "RequestedHallId");

                    b.ToTable("ROOM_CHANGE_REQUESTS");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("S_ID");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("S_BLD_GRP");

                    b.Property<string>("BoarderNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("S_BOARDER_NO");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_DEPARTMENT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("S_EMAIL");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_EMERGENCY_NAME");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("S_EMERGENCY_PHONE");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_FACULTY");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_FATHER_NAME");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("S_GENDER");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("S_MOBILE");

                    b.Property<string>("MotherName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_MOTHER_NAME");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("S_PRM_ADDR");

                    b.Property<string>("Religion")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("S_RELIGION");

                    b.Property<int>("Semester")
                        .HasColumnType("int")
                        .HasColumnName("S_SEMESTER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("S_STATUS");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("S_NAME");

                    b.HasKey("StudentId");

                    b.HasIndex("BoarderNo")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedHall", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("AssignedHalls")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("AssignedHalls")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedRoom", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("AssignedRooms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Room", "Room")
                        .WithMany("AssignedRooms")
                        .HasForeignKey("RoomId", "AssignedHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.AssignedHall", "AssignedHall")
                        .WithMany("AssignedRooms")
                        .HasForeignKey("StudentId", "AssignedHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedHall");

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.BoarderRegistry", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.HallAdmin", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("HallAdmins")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId", "HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Room", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany("Rooms")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomApplicationRequest", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomAssignment", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.RoomChangeRequest", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.Student", "Student")
                        .WithMany("RoomChangeRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidentialHallManagement.Core.Entities.Room", "RequestedRoom")
                        .WithMany()
                        .HasForeignKey("RequestedRoomId", "RequestedHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedRoom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Student", b =>
                {
                    b.HasOne("ResidentialHallManagement.Core.Entities.BoarderRegistry", "BoarderRegistry")
                        .WithOne()
                        .HasForeignKey("ResidentialHallManagement.Core.Entities.Student", "BoarderNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoarderRegistry");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.AssignedHall", b =>
                {
                    b.Navigation("AssignedRooms");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Hall", b =>
                {
                    b.Navigation("AssignedHalls");

                    b.Navigation("HallAdmins");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Room", b =>
                {
                    b.Navigation("AssignedRooms");
                });

            modelBuilder.Entity("ResidentialHallManagement.Core.Entities.Student", b =>
                {
                    b.Navigation("AssignedHalls");

                    b.Navigation("AssignedRooms");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("RoomChangeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
